import { BibleBook } from './types';

export const bibleBooks: BibleBook[] = [
  // Old Testament
  { name: 'Gênesis', chapters: 50, testament: 'Old' },
  { name: 'Êxodo', chapters: 40, testament: 'Old' },
  { name: 'Levítico', chapters: 27, testament: 'Old' },
  { name: 'Números', chapters: 36, testament: 'Old' },
  { name: 'Deuteronômio', chapters: 34, testament: 'Old' },
  { name: 'Josué', chapters: 24, testament: 'Old' },
  { name: 'Juízes', chapters: 21, testament: 'Old' },
  { name: 'Rute', chapters: 4, testament: 'Old' },
  { name: '1 Samuel', chapters: 31, testament: 'Old' },
  { name: '2 Samuel', chapters: 24, testament: 'Old' },
  { name: '1 Reis', chapters: 22, testament: 'Old' },
  { name: '2 Reis', chapters: 25, testament: 'Old' },
  { name: '1 Crônicas', chapters: 29, testament: 'Old' },
  { name: '2 Crônicas', chapters: 36, testament: 'Old' },
  { name: 'Esdras', chapters: 10, testament: 'Old' },
  { name: 'Neemias', chapters: 13, testament: 'Old' },
  { name: 'Ester', chapters: 10, testament: 'Old' },
  { name: 'Jó', chapters: 42, testament: 'Old' },
  { name: 'Salmos', chapters: 150, testament: 'Old' },
  { name: 'Provérbios', chapters: 31, testament: 'Old' },
  { name: 'Eclesiastes', chapters: 12, testament: 'Old' },
  { name: 'Cânticos', chapters: 8, testament: 'Old' },
  { name: 'Isaías', chapters: 66, testament: 'Old' },
  { name: 'Jeremias', chapters: 52, testament: 'Old' },
  { name: 'Lamentações', chapters: 5, testament: 'Old' },
  { name: 'Ezequiel', chapters: 48, testament: 'Old' },
  { name: 'Daniel', chapters: 12, testament: 'Old' },
  { name: 'Oseias', chapters: 14, testament: 'Old' },
  { name: 'Joel', chapters: 3, testament: 'Old' },
  { name: 'Amós', chapters: 9, testament: 'Old' },
  { name: 'Obadias', chapters: 1, testament: 'Old' },
  { name: 'Jonas', chapters: 4, testament: 'Old' },
  { name: 'Miqueias', chapters: 7, testament: 'Old' },
  { name: 'Naum', chapters: 3, testament: 'Old' },
  { name: 'Habacuque', chapters: 3, testament: 'Old' },
  { name: 'Sofonias', chapters: 3, testament: 'Old' },
  { name: 'Ageu', chapters: 2, testament: 'Old' },
  { name: 'Zacarias', chapters: 14, testament: 'Old' },
  { name: 'Malaquias', chapters: 4, testament: 'Old' },
  // New Testament
  { name: 'Mateus', chapters: 28, testament: 'New' },
  { name: 'Marcos', chapters: 16, testament: 'New' },
  { name: 'Lucas', chapters: 24, testament: 'New' },
  { name: 'João', chapters: 21, testament: 'New' },
  { name: 'Atos', chapters: 28, testament: 'New' },
  { name: 'Romanos', chapters: 16, testament: 'New' },
  { name: '1 Coríntios', chapters: 16, testament: 'New' },
  { name: '2 Coríntios', chapters: 13, testament: 'New' },
  { name: 'Gálatas', chapters: 6, testament: 'New' },
  { name: 'Efésios', chapters: 6, testament: 'New' },
  { name: 'Filipenses', chapters: 4, testament: 'New' },
  { name: 'Colossenses', chapters: 4, testament: 'New' },
  { name: '1 Tessalonicenses', chapters: 5, testament: 'New' },
  { name: '2 Tessalonicenses', chapters: 3, testament: 'New' },
  { name: '1 Timóteo', chapters: 6, testament: 'New' },
  { name: '2 Timóteo', chapters: 4, testament: 'New' },
  { name: 'Tito', chapters: 3, testament: 'New' },
  { name: 'Filemom', chapters: 1, testament: 'New' },
  { name: 'Hebreus', chapters: 13, testament: 'New' },
  { name: 'Tiago', chapters: 5, testament: 'New' },
  { name: '1 Pedro', chapters: 5, testament: 'New' },
  { name: '2 Pedro', chapters: 3, testament: 'New' },
  { name: '1 João', chapters: 5, testament: 'New' },
  { name: '2 João', chapters: 1, testament: 'New' },
  { name: '3 João', chapters: 1, testament: 'New' },
  { name: 'Judas', chapters: 1, testament: 'New' },
  { name: 'Apocalipse', chapters: 22, testament: 'New' },
];

export const translations = {
  pt: {
    appTitle: "Bíblia Online",
    devotional: "Devocional Diário",
    chat: "Chat Teológico",
    settings: "Configurações",
    searchPlaceholder: "Buscar...",
    recent: "Recentes",
    clear: "Limpar",
    books: "Livros",
    all: "Todos",
    oldTestament: "Antigo",
    newTestament: "Novo",
    chapter: "Capítulo",
    bibleReading: "Leitura Bíblica",
    listenChapter: "Ouvir Capítulo",
    stopReading: "Parar Leitura",
    loadingAudio: "Carregando...",
    listeningTo: "Ouvindo",
    excerpt: "Trecho",
    explainVerse: "Explicar Versículo",
    copy: "Copiar",
    share: "Compartilhar",
    explanation: "Explicação",
    backToActions: "Voltar para ações",
    resultsFor: "Resultados para",
    noResults: "Nenhum resultado encontrado.",
    context: "Contexto",
    dailyDevotionalTitle: "Devocional do Dia",
    prayer: "Oração",
    chatWelcome: "Olá! Sou seu assistente de estudos bíblicos. Como posso ajudar você a compreender melhor as escrituras hoje?",
    chatPlaceholder: "Pergunte sobre teologia, história ou versículos...",
    send: "Enviar",
    theme: "Cor de Fundo",
    fontSize: "Tamanho da Fonte",
    fontFamily: "Tipo de Fonte",
    textAlign: "Alinhamento do Texto",
    light: "Claro",
    sepia: "Sépia",
    dark: "Escuro",
    serif: "Serifa",
    sans: "Sem Serifa",
    done: "Concluído",
    privacy: "Política de Privacidade",
    terms: "Termos de Uso",
    fullScreen: "Tela Cheia",
    exitFullScreen: "Sair da Tela Cheia",
    viewMode: "Modo de Visualização"
  },
  en: {
    appTitle: "Bible Online",
    devotional: "Daily Devotional",
    chat: "Theological Chat",
    settings: "Settings",
    searchPlaceholder: "Search...",
    recent: "Recent",
    clear: "Clear",
    books: "Books",
    all: "All",
    oldTestament: "Old",
    newTestament: "New",
    chapter: "Chapter",
    bibleReading: "Bible Reading",
    listenChapter: "Listen to Chapter",
    stopReading: "Stop Reading",
    loadingAudio: "Loading...",
    listeningTo: "Listening to",
    excerpt: "Part",
    explainVerse: "Explain Verse",
    copy: "Copy",
    share: "Share",
    explanation: "Explanation",
    backToActions: "Back to actions",
    resultsFor: "Results for",
    noResults: "No results found.",
    context: "Context",
    dailyDevotionalTitle: "Daily Devotional",
    prayer: "Prayer",
    chatWelcome: "Hello! I am your bible study assistant. How can I help you understand the scriptures today?",
    chatPlaceholder: "Ask about theology, history, or verses...",
    send: "Send",
    theme: "Background Color",
    fontSize: "Font Size",
    fontFamily: "Font Family",
    textAlign: "Text Alignment",
    light: "Light",
    sepia: "Sepia",
    dark: "Dark",
    serif: "Serif",
    sans: "Sans Serif",
    done: "Done",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
    fullScreen: "Full Screen",
    exitFullScreen: "Exit Full Screen",
    viewMode: "View Mode"
  },
  es: {
    appTitle: "Biblia Online",
    devotional: "Devocional Diario",
    chat: "Chat Teológico",
    settings: "Configuraciones",
    searchPlaceholder: "Buscar...",
    recent: "Recientes",
    clear: "Limpiar",
    books: "Libros",
    all: "Todos",
    oldTestament: "Antiguo",
    newTestament: "Nuevo",
    chapter: "Capítulo",
    bibleReading: "Lectura Bíblica",
    listenChapter: "Escuchar Capítulo",
    stopReading: "Detener Lectura",
    loadingAudio: "Cargando...",
    listeningTo: "Escuchando",
    excerpt: "Parte",
    explainVerse: "Explicar Versículo",
    copy: "Copiar",
    share: "Compartir",
    explanation: "Explicación",
    backToActions: "Volver a acciones",
    resultsFor: "Resultados para",
    noResults: "No se encontraron resultados.",
    context: "Contexto",
    dailyDevotionalTitle: "Devocional del Día",
    prayer: "Oración",
    chatWelcome: "¡Hola! Soy tu asistente de estudios bíblicos. ¿Cómo puedo ayudarte a comprender mejor las escrituras hoy?",
    chatPlaceholder: "Pregunta sobre teología, historia o versículos...",
    send: "Enviar",
    theme: "Color de Fondo",
    fontSize: "Tamaño de Fuente",
    fontFamily: "Tipo de Fuente",
    textAlign: "Alineación del Texto",
    light: "Claro",
    sepia: "Sepia",
    dark: "Oscuro",
    serif: "Serifa",
    sans: "Sin Serifa",
    done: "Listo",
    privacy: "Política de Privacidad",
    terms: "Términos de Uso",
    fullScreen: "Pantalla Completa",
    exitFullScreen: "Salir de Pantalla Completa",
    viewMode: "Modo de Visualización"
  }
};

export const normalizeBookName = (name: string): string => {
  return name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, '-');
};

export const findBookByNormalizedName = (normalizedName: string): BibleBook | undefined => {
  const target = normalizeBookName(normalizedName);
  return bibleBooks.find(b => normalizeBookName(b.name) === target);
};